### ISSUE TITLE
Configuration 

### ISSUE THREAD

**Issue by Ra7t0r** [buxxi/MMM-IndoorTemperature-Endpoint#1]
Hello.
Is an additional configuration that must be set in order to this module work properly?
A tcp port correspond to a server?
Or the module automatically creates a listening socket?

**Comment by buxxi** [comment]
Hi,

There is no more configuration for the module. It adds itself to the existing magicmirror-application as its own path, so if you can view the magicmirror on http://localhost:8080 the path to the module is http://localhost:8080/indoor-temperature.

**Comment by Ra7t0r** [comment]
Hi, Thanks for your reply.
is it possible to display the value on MagicMirror as well, after receiving it via post request?
Something like:

{
module: "MMM-IndoorTemperature-Endpoint",
                        position: "top_right",
                        header: “Temp DH11",
                        config: {}
}

**Comment by buxxi** [comment]
That's not really what this module is for. It forwards it to other modules that listens for the INDOOR_TEMPERATURE-notification, like the standard [current weather](https://docs.magicmirror.builders/modules/currentweather.html#configuration-options)-module that is responsible to display it. Just enable `showIndoorTemperature: true` in the currentweather-configuration and it should be displayed.

Should probably clarify that in the readme.

**Comment by buxxi** [comment]
Updated the Readme with what the module does.

I have no intention to actually make it display anything since this was created only to use my outdated Tellstick with my MagicMirror and I'm perfectly fine with using the current weather-module. If you actually want it do display by its own it's probably a very easy module to create that listens to the notification and presents it.
